sudo: required
services:
  - docker

before_install:
  - docker build -t simonlambrix/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true simonlambrix/react-test npm test

after_success:
  - docker build -t simonlambrix/multi-client ./client
  - docker build -t simonlambrix/multi-nginx ./nginx
  - docker build -t simonlambrix/multi-server ./server
  - docker build -t simonlambrix/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push simonlambrix/multi-client   
  - docker push simonlambrix/multi-nginx   
  - docker push simonlambrix/multi-server   
  - docker push simonlambrix/multi-worker   
  
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-638777877141" 
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY